<?php

if( ! defined("EDD_HS::VERSION") ) {
	header( 'Status: 403 Forbidden' );
	header( 'HTTP/1.1 403 Forbidden' );
	exit;
}

/**
 * This class takes care of AJAX requests from HelpScout
 */
class EDD_HS_Ajax {

	/**
	 * Constructor
	 */
	public function __construct() {
		// Double add_action because we want it to work when you're logged in too
		add_action( 'wp_ajax_nopriv_hs_action', array( $this, 'ajax_action' ) );
		add_action( 'wp_ajax_hs_action', array( $this, 'ajax_action' ) );
	}

	/**
	 * Handle AJAX actions
	 */
	public function ajax_action() {
		// The nonces generated by the EDD HelpScout Integration get user ID 0, so we need to check the nonce versus that User ID
		wp_set_current_user( 0 );

		// Use wp_verify_nonce and check for a 1 return, which means a nonce is valid for 12 hours instead of the default 24
		if ( 1 !== wp_verify_nonce( $_REQUEST['nonce'], 'hs-edd-integration' ) ) {
			die( '-1' );
		}

		switch ( $_REQUEST['hs_action'] ) {
			case 'deactivate':
				$this->handle_deactivation_request();
				break;
			default:
				break;
		}
		die();
	}

	/**
	 * Deactivates a site
	 */
	private function handle_deactivation_request() {
		echo edd_software_licensing()->delete_site( $_REQUEST['license_id'], $_REQUEST['site_url'] );
	}
}
